export const FETCH_MERCHANTS="FETCH_MERCHANTS";
export type FETCH_MERCHANTS =typeof FETCH_MERCHANTS;
export const FETCH_MERCHANTS_SUCCESS="FETCH_MERCHANTS_SUCCESS";
export type FETCH_MERCHANTS_SUCCESS=typeof FETCH_MERCHANTS_SUCCESS;
export const FETCH_MERCHANTS_FAILURE="FETCH_MERCHANTS_FAILURE";
export type FETCH_MERCHANTS_FAILURE=typeof FETCH_MERCHANTS_FAILURE
export const RESET_MERCHANTS="RESET_MERCHANTS";
export type RESET_MERCHANTS=typeof RESET_MERCHANTS;