export const FETCH_MERCHANTS="FETCH_MERCHANTS";
export type FETCH_MERCHANTS =typeof FETCH_MERCHANTS;
export const FETCH_MERCHANTS_SUCCESS="FETCH_MERCHANTS_SUCCESS";
export type FETCH_MERCHANTS_SUCCESS=typeof FETCH_MERCHANTS_SUCCESS;
export const FETCH_MERCHANTS_FAILURE="FETCH_MERCHANTS_FAILURE";
export type FETCH_MERCHANTS_FAILURE=typeof FETCH_MERCHANTS_FAILURE
export const RESET_MERCHANTS="RESET_MERCHANTS";
export type RESET_MERCHANTS=typeof RESET_MERCHANTS;


// //fetch merchant
export const FETCH_MERCHANT="FETCH_MERCHANT";
export const FETCH_MERCHANT_SUCCESS="FETCH_MERCHANT_SUCCESS";
export const FETCH_MERCHANT_FAILURE="FETCH_MERCHANT_FAILURE";
export const RESET_ACTIVE_MERCHANT="RESET_ACTIVE_MERCHANT";

export type FETCH_MERCHANT=typeof FETCH_MERCHANT
export type FETCH_MERCHANT_SUCCESS=typeof FETCH_MERCHANT_SUCCESS;
export type FETCH_MERCHANT_FAILURE=typeof FETCH_MERCHANT_FAILURE;
export type RESET_ACTIVE_MERCHANT=typeof RESET_ACTIVE_MERCHANT;
